networks:
  internal:
  mongodb:
    external: true
  cutup:
    external: true

services:
  frontend:
    image: jtools-frontend:3.14.0
    container_name: jtools-frontend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 8602:8602
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  backend:
    image: jtools-backend:3.14.0
    container_name: jtools-backend
    build:
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/config.toml:/app/config.toml:ro
    networks:
      - internal
      - mongodb
      - cutup
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
