FROM python:3.10-slim

ENV TZ Asia/Shanghai

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install \
    -r requirements.txt \
    --no-cache-dir \
    --no-compile \
    --disable-pip-version-check

COPY backend .

CMD ["python", "main.py"]
