FROM oven/bun:1-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/bun.lockb /app

RUN bun install --prod --frozen-lockfile

COPY frontend /app

RUN bun run build

FROM caddy:2.7.4-alpine

WORKDIR /app

COPY --from=build /app/dist ./static