FROM node:19.8-alpine3.16 AS build

WORKDIR /app

RUN npm install -g pnpm

COPY frontend/package.json /app

RUN pnpm install --loglevel warn

COPY frontend /app

RUN pnpm build -l warn

FROM caddy:2.6.3-alpine

WORKDIR /app

COPY --from=build /app/dist ./static