FROM oven/bun:1-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/bun.lockb .
RUN bun install --prod --frozen-lockfile

COPY frontend .
RUN bun run build

FROM caddy:2.7-alpine

WORKDIR /app

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist .