version: "3"
services:
  main:
    image: jianshumicrofeatures:1.4.0
    build: .
    ports:
      - "8602:8602"
    volumes:
      - "./config.yaml:/app/config.yaml"
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3