FROM python:3.12-slim

ENV TZ Asia/Shanghai

WORKDIR /app

COPY backend/pyproject.toml backend/uv.lock .

RUN --mount=from=ghcr.io/astral-sh/uv:0.4.0,source=/uv,target=/bin/uv \
    uv sync --frozen --no-dev --no-cache

COPY backend .

ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "main.py"]
