version: "3"

networks:
  internal:
  mongodb:
    external: true
  cutup:
    external: true

services:
  frontend:
    image: jtools-frontend:3.11.0
    container_name: jtools-frontend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 8602:8602
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 48M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 5s
  backend:
    image: jtools-backend:3.11.0
    container_name: jtools-backend
    build:
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/config.yaml:/app/config.yaml:ro
    networks:
      - internal
      - mongodb
      - cutup
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 96M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 5s
