version: "3"

networks:
  mongodb:
    external: true
  cutup:
    external: true

services:
  main:
    image: jianshu-micro-features:2.11.0
    build: .
    ports:
      - 8602:8602
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - mongodb
      - cutup
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 192M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1s
