version: "3"
services:
  main:
    image: jianshumicrofeatures:1.4.3
    build: .
    ports:
      - "8602:8602"
    volumes:
      - "./config.yaml:/app/config.yaml"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 192M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1s
