[tool.poetry]
name = "JianshuMicroFeatures"
version = "1.4.1"
description = "简书小工具集"
authors = ["FHU-yezi <yehaowei20060411@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pywebio = "^1.6.0"
JianshuResearchTools = "2.10.0"
jieba = "^0.42.1"
qrcode = "^7.3.1"
pyecharts = "^1.9.1"
PyYAML = "^6.0"
tomd = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
