[tool.poetry]
name = "jtools"
version = "3.7.0"
description = "探索未知"
authors = ["yezi <yehaowei20060411@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
motor = "^3.3.1"
jianshuresearchtools = "^2.11.0"
sspeedup = {version = "^0.23.0", extras = ["logging", "config", "api-litestar"]}
uvicorn = "^0.23.2"
httptools = "^0.6.0"
uvloop = "^0.17.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"
pyright = "^1.1.333"
watchfiles = "^0.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]

select = ["A", "ANN", "B", "C", "E", "F", "I", "N", "RET", "S", "SIM", "UP", "W"]

ignore = ["ANN101", "ANN102", "ANN401", "C901", "E501", "S104"]

target-version = "py38"