[tool.poetry]
name = "jtools"
version = "3.7.0"
description = "探索未知"
authors = ["yezi <yehaowei20060411@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
motor = "^3.3.0"
jianshuresearchtools = "^2.11.0"
sspeedup = {version = "^0.24.0", extras = ["logging", "config", "api-litestar"]}
uvicorn = "^0.23.0"
httptools = "^0.6.0"
uvloop = "^0.19.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.0"
pyright = "^1.1.0"
watchfiles = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]

select = [
    "A", "ANN", "ASYNC", "B", "BLE",
    "C4", "E", "F", "I", "ICN",
    "ISC", "N", "PIE", "Q", "RET",
    "RSE", "RUF", "S", "SIM", "SLF",
    "TCH", "UP", "W"
]

ignore = ["ANN101", "ANN401", "BLE001", "RUF001", "RUF002", "RUF003"]

target-version = "py38"