article-wordcloud-generator:
    status: NORMAL
    reason: null
    last_update_time: null
    data_update_freq: null
    data_count: null
    data_source: null
JPEP-FTN-market-analyzer:
    status: DOWNGRADED
    reason: 受政策变动影响，简书积分兑换平台自 2024.7.3 9:49 起暂停运营。
    last_update_time:
        collection: FTN_trade_orders
        sort_key: fetchTime
        sort_direction: desc
    data_update_freq: 十分钟一次
    data_count:
      collection: FTN_trade_orders
      mode: estimated
    data_source:
        简书积分兑换平台 - 贝市: https://www.jianshubei.com/bei
lottery-analyzer:
    status: DOWNGRADED
    reason: 受简书运营调整影响，大转盘抽奖已于 2024.4.28 13:20 下线。
    last_update_time:
      collection: lottery_win_records
      sort_key: time
      sort_direction: desc
    data_update_freq: 十分钟一次
    data_count:
      collection: lottery_win_records
      mode: estimated
    data_source:
        简书 - 天天抽奖: https://www.jianshu.com/mobile/lottery
lottery-reward-record-viewer:
    status: DOWNGRADED
    reason: 受简书运营调整影响，大转盘抽奖已于 2024.4.28 13:20 下线。
    last_update_time:
      collection: lottery_win_records
      sort_key: time
      sort_direction: desc
    data_update_freq: 十分钟一次
    data_count:
      collection: lottery_win_records
      mode: estimated
    data_source:
        简书 - 天天抽奖: https://www.jianshu.com/mobile/lottery
LP-recommend-checker:
    status: DOWNGRADED
    reason: 受简书运营调整影响，LP 理事会超级权重不再发放，故取消相关推文限制。
    last_update_time: null
    data_update_freq: null
    data_count: null
    data_source:
        简书 - 专题 - 理事会点赞汇总: https://www.jianshu.com/c/f61832508891
on-rank-article-viewer:
    status: DOWNGRADED
    reason: 受简书运营调整影响，文章收益排行榜已于 2024.6.21 下线。
    last_update_time:
      collection: article_earning_ranking_records
      sort_key: date
      sort_direction: desc
    data_update_freq: 每天凌晨 1:00
    data_count:
      collection: article_earning_ranking_records
      mode: estimated
    data_source:
        简书 - 简书钻每日发放总榜: https://www.jianshu.com/fp/notice/now
URL-scheme-convertor:
    status: NORMAL
    reason: null
    last_update_time: null
    data_update_freq: null
    data_count: null
    data_source: null
VIP-info-viewer:
    status: NORMAL
    reason: null
    last_update_time: null
    data_update_freq: null
    data_count: null
    data_source: null
VIP-profit-compute:
    status: NORMAL
    reason: null
    last_update_time: null
    data_update_freq: null
    data_count: null
    data_source:
        简书 - 简书会员大使: https://www.jianshu.com/mobile/club/ambassador
