name: Static Check

on:
  push:

jobs:
  static-check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python
      run: uv python install 3.12
    - name: Install Dependencies
      run: uv sync --all-extras
    - name: Lint With Ruff
      run: uv run ruff check --output-format=github .
    - name: Type checking with Pyright
      run: uv run pyright --warnings .
  static-check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
            version: latest
      - name: Run Biome
        run: biome ci .