name: Static Check

on:
  push:
  workflow_call:

jobs:
  static-check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --all-extras --no-root
      - name: Lint With Ruff
        run: poetry run ruff check --output-format=github .
      - name: Type checking with Pyright
        run: poetry run pyright --warnings .
  static-check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Lint with Eslint
        run: bun run check:eslint
      - name: Style check with Prettier
        run: bun run check:prettier
