name: Static Check

on:
  push:

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python
      run: uv python install 3.12
    - name: Install Dependencies
      run: uv sync --all-extras
    - name: Lint With Ruff
      run: uv run ruff check --output-format=github .
    - name: Type checking with Pyright
      run: uv run pyright --warnings .